<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="rrbot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="mass" value=".01" /> <!-- arbitrary value for mass -->
  <xacro:property name="width" value="0.1" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="height1" value="1" /> <!-- Link 1 -->
  <xacro:property name="height2" value="1" /> <!-- Link 2 -->
  <xacro:property name="height3" value="1" /> <!-- Link 3 -->
  <xacro:property name="height4" value="1.2" /> <!-- Link 3 -->
  <xacro:property name="camera_link" value="0.05" /> <!-- Size of square 'camera' box -->
  <xacro:property name="axel_offset" value="0.05" /> <!-- Space btw top of beam and the each joint -->

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find rbe500GroupProject)/urdf/rrbot.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find rbe500GroupProject)/urdf/materials.xacro" />

  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="world"/>

  <joint name="joint0" type="revolute">
    <parent link="world"/>
    <child link="link1"/>
    <limit effort="1000.0" lower="-3.14159" upper="3.14159" velocity="10"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- Base Link -->
  <link name="link1">
    <collision>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height1}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height1}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${0}" ixy="0.0" ixz="0.0"
	  iyy="${0}" iyz="0.0"
	  izz="${0}"/>
    </inertial>
  </link>

  <joint name="joint1" type="fixed">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="0 0 ${height1+width/2}" rpy="0 0 0"/>
  </joint>

  <!-- Middle Link -->
  <link name="link2">
    <collision>
      <origin xyz="0 ${height2/2-(width/2)} 0" rpy="1.57 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height2}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 ${height2/2-(width/2)} 0" rpy="1.57 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height2}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
       <origin xyz="0 ${height2/2-(width/2)} ${width/2}" rpy="1.57 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${0}" ixy="0.0" ixz="0.0"
	  iyy="${0}" iyz="0.0"
	  izz="${0}"/>
    </inertial>
  </link>

  <joint name="joint2" type="continuous">
    <limit effort="1000.0" lower="-3.14159" upper="3.14159" velocity="10"/>
    <parent link="link2"/>
    <child link="link3"/>
    <origin xyz="0 ${height2-(width)} 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
	<gravity>0</gravity>
  </joint>

  <!-- Top Link -->
  <link name="link3">
    <collision>
      <origin xyz="0 ${height3/2-width} ${width}" rpy="1.57 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height3}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 ${height3/2-(width/2)} ${width}" rpy="1.57 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height3}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 ${height3/2-width} ${width}" rpy="1.57 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${0}" ixy="0.0" ixz="0.0"
	  iyy="${0}" iyz="0.0"
	  izz="${0}"/>
    </inertial>
	<gravity>0</gravity>
  </link>

  <!-- prismatic Link -->
 <joint name="prismatic" type="prismatic">
    <parent link="link3"/>
    <child link="link4"/>
    <limit effort="1000.0" lower="0" upper="${height1+(width/2)}" velocity="0.5"/>
    <origin xyz="0 ${height3} 0" rpy="0 0 0"/>
    <axis xyz="0 0 -1"/>
    <dynamics damping="0.7"/>
	<gravity>0</gravity>
  </joint>

<link name="link4">
    <collision>
      <origin xyz="0 0 ${height4/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height4}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height4/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height4}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height4/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height4*height4)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height4*height4 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
	<gravity>0</gravity>
  </link>

  <transmission name="tran0">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint0">
<hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor0">
<hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>


  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint2">
<hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
<hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

 <transmission name="prismatic">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="prismatic">
<hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor3">
<hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

</robot>
